### ISSUE TITLE
GoogleService-Info need ! 

### ISSUE THREAD

**Issue by League2EB** [gonzob7/FBLAPrep#1]
Hello gonzob7
I wanted to try this APP, but I tried to compile it
But tell me that I lost GoogleService-Info
How do I get the GoogleService Info file? Or can you provide the upload again here?
Thank you for your help

**Comment by iOSGonzo** [comment]
Hi, thank you for letting me know about this problem while compiling!
I'm not entirely sure why the GoogleService-Info file is not uploading with the project.

First, have you tried checking if this file is in the "other" folder?

<img width="1181" alt="GoogleService plist" src="https://user-images.githubusercontent.com/24580848/54241297-a64c7300-44dd-11e9-98cb-731d2a22ef86.png">

If not, I just directly uploaded the file through GitHub. You should be able to clone and compile successfully. If there are any more problems, please let me know thank you!

**Comment by League2EB** [comment]
> Hi, thank you for letting me know about this problem while compiling!
> I'm not entirely sure why the GoogleService-Info file is not uploading with the project.
> 
> First, have you tried checking if this file is in the "other" folder?
> 
> <img alt="GoogleService plist" width="1181" src="https://user-images.githubusercontent.com/24580848/54241297-a64c7300-44dd-11e9-98cb-731d2a22ef86.png">
> 
> If not, I just directly uploaded the file through GitHub. You should be able to clone and compile successfully. If there are any more problems, please let me know thank you!

A: hi! When I re-clone the project, I see a GoogleService Info. Plist
Thank you very much for your help.
In addition, is it possible for the APP to be available on the APP Store?

**Comment by gonzob7** [comment]
Hey! Glad to hear it's compiling now. And currently, I do not have plans to upload this to the app store since it was created for a competition.

**Comment by iOSGonzo** [comment]
> > Hi, thank you for letting me know about this problem while compiling!
> > I'm not entirely sure why the GoogleService-Info file is not uploading with the project.
> > First, have you tried checking if this file is in the "other" folder?
> > <img alt="GoogleService plist" width="1181" src="https://user-images.githubusercontent.com/24580848/54241297-a64c7300-44dd-11e9-98cb-731d2a22ef86.png">
> > If not, I just directly uploaded the file through GitHub. You should be able to clone and compile successfully. If there are any more problems, please let me know thank you!
> 
> A: hi! When I re-clone the project, I see a GoogleService Info. Plist
> Thank you very much for your help.
> In addition, is it possible for the APP to be available on the APP Store?

Hey! Glad to hear it's compiling now. And currently, I do not have plans to upload this to the app store since it was created for a competition.
